### ISSUE TITLE
Check it out!

### ISSUE THREAD

**Issue by 123452123-codr** [Anjor-Srivastava/Anjor-Srivastava#1]
Well, I have noticed that the spelling of the word "some" in the 4th sentence is incorrect. And, actually you have said the truth about your repos in the 4th line.....🤣🤣🤣😂

**Comment by Anjor-Srivastava** [comment]
Shut up!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by 123452123-codr** [comment]
Really....you said the truth about all your repos in that line.... They and you deserve that! 🤣😂
